context:
  version: "15.8.2"

package:
  name: sql-formatter
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/sql-formatter/-/sql-formatter-${{ version }}.tgz
  sha256: ef65074d6c93c06a753c31006a114c0df999db7e57ab92e3054e1dfd66768fb3

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - sql-formatter --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A whitespace formatter for different query languages
  homepage: https://github.com/sql-formatter-org/sql-formatter
  repository: https://github.com/sql-formatter-org/sql-formatter

extra:
  recipe-maintainers:
    - danielnachun
