context:
  version: "15.6.12"

package:
  name: sql-formatter
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/sql-formatter/-/sql-formatter-${{ version }}.tgz
  sha256: 7db98abe63c33570e546a774ef934764c52b5ca8654d3a90e2fe6ac33cd85ec6

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - sql-formatter --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A whitespace formatter for different query languages
  homepage: https://github.com/sql-formatter-org/sql-formatter
  repository: https://github.com/sql-formatter-org/sql-formatter

extra:
  recipe-maintainers:
    - danielnachun
