context:
  version: "15.9.0"

package:
  name: sql-formatter
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/sql-formatter/-/sql-formatter-${{ version }}.tgz
  sha256: ca4475f0c03b22c8803dcd05f13c02961dd8363ae4f112b2a3d071edf5fa095f

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - sql-formatter --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A whitespace formatter for different query languages
  homepage: https://github.com/sql-formatter-org/sql-formatter
  repository: https://github.com/sql-formatter-org/sql-formatter

extra:
  recipe-maintainers:
    - danielnachun
