context:
  version: "15.7.3"

package:
  name: sql-formatter
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/sql-formatter/-/sql-formatter-${{ version }}.tgz
  sha256: 5ec54da8958d4ad9f6c948a8032ce55a2444361a9a9223766f8b4e75d2b29819

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - sql-formatter --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A whitespace formatter for different query languages
  homepage: https://github.com/sql-formatter-org/sql-formatter
  repository: https://github.com/sql-formatter-org/sql-formatter

extra:
  recipe-maintainers:
    - danielnachun
