context:
  version: "15.6.3"

package:
  name: sql-formatter
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/sql-formatter/-/sql-formatter-${{ version }}.tgz
  sha256: 3119011d337a0564805064c41bf1789be9836260fcdeb96e8b97cbdcfe20fce8

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - sql-formatter --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: A whitespace formatter for different query languages
  homepage: https://github.com/sql-formatter-org/sql-formatter
  repository: https://github.com/sql-formatter-org/sql-formatter

extra:
  recipe-maintainers:
    - danielnachun
